name: DB Manual Run
on:
  workflow_dispatch:

jobs:
  Test:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        id: jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true

      # Setup maven because the test project is a maven project
      - name: Setup Maven
        id: maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: '3.8.4'

      - name: Ping Oracle Databse Host
        run: ping -c 10 aras0001.ah.nl

      - name: Start tests
        run: mvn clean verify

## After tests run, upload the Single Page Report to the artifactory
#      - name: Single Page Report
#        if: always()
#        id: singlepagereport
#        uses: actions/upload-artifact@v3
#        with:
#          name: single_page_report
#          path: ${{ github.workspace }}/target/site/serenity/serenity-summary.html
#  #          if-no-files-found: error
#
#      - name: Upload Full Test Report
#        if: always()
#        uses: actions/upload-artifact@v3
#        with:
#          name: Full Report
#          path: ${{ github.workspace }}/target/site/serenity

